name: github-actions-first-wf

on: [push]

jobs:
  checkout-code:
    runs-on: windows-machine
    steps:
      - uses: actions/checkout@v2

  check-versions:
    runs-on: windows-machine
    steps:
      - run: ng version

  lint-test:
    runs-on: windows-machine
    steps:
      - run: ng lint

  unit-test:
    runs-on: windows-machine
    steps:
      - run: ng test

  build-app:
    runs-on: windows-machine
    steps:
      - run: ng build

  deploy-app:
    runs-on: windows-machine
    steps:
      - run: xcopy dist\clase6 C:\inetpub\wwwroot\romell\dev /s /y /q

  completed-job:
    runs-on: windows-machine
    steps:
      - run: echo "Job completed"
